base_url = "https://driffaud.fr"
title = "Adrien Driffaud"
default_language = "fr"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true

[extra]

[translations]
astronomy = "Astronomie"
gallery = "Galerie"
resume = "CV"
full = "Cliquer sur l'image pour l'afficher en résolution maximale"
flag = "🇫🇷"

[languages.en]

[languages.en.translations]
astronomy = "Astronomy"
gallery = "Gallery"
resume = "Resume"
full = "Click on the picture to show the full resolution"
flag = "🇺🇸"
