baseURL = "/"
languageCode = "en-us"
title = "Adrien Driffaud"
theme = "resume"

[blackfriday]
    hrefTargetBlank = true

[params]
    firstName = "Adrien"
    lastName = "Driffaud"
    address = "Toulouse, France"
    contactNote = "Software Development Engineer"
    profileImage = "img/avatar.jpg"
    email = "adrien@driffaud.fr"
    description = "Software Platform Engineer with experience leveraging agile, DevOps, and CI/CD to manage large scale distributed platforms both on prem and in public cloud."
    # favicon = "images/favicon.ico"
    # what sections
    showSkills = true
    showProjects = false
    showOpenSource = false
    showPublications = false
    showExperience = true
    showEducation = true

    showQr = true

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/adriffaud/"

[[params.handles]]
    name = "Twitter"
    link = "https://twitter.com/adriffaud"